#############################################################################
# Makefile for building: build/namas_main
# Generated by qmake (3.1) (Qt 5.9.1)
# Project:  namas_main.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile namas_main.pro CONFIG+=PC
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = @echo compiling $< && gcc
CXX           = @echo compiling $< && g++
DEFINES       = -DPC -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -Isrc -Iinclude -Iui -Ilib -isystem /usr/local/include -isystem /usr/include/qt -isystem /usr/include/qt/QtMultimediaWidgets -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtMultimedia -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -Imoc -isystem /usr/include/libdrm -Iui -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = namas_main1.0.0
DISTDIR = /home/justas/work/namas/namas_main/obj/namas_main1.0.0
LINK          = @echo linking $@ && g++
LFLAGS        = -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) -lQt5MultimediaWidgets -lpulse-mainloop-glib -lpulse -lglib-2.0 -lQt5Widgets -lQt5Multimedia -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/info_widget.cpp \
		src/main.cpp \
		src/MainWindow.cpp \
		src/Bath_Room_win.cpp \
		src/Bed_Room_win.cpp \
		src/Work_Room_win.cpp \
		src/Corridor_win.cpp \
		src/TCP.cpp \
		src/Room.cpp \
		src/Alarm.cpp \
		src/Logger.cpp \
		src/Camera.cpp rcc/qrc_res.cpp \
		moc/moc_info_widget.cpp \
		moc/moc_MainWindow.cpp \
		moc/moc_Bath_Room_win.cpp \
		moc/moc_Bed_Room_win.cpp \
		moc/moc_Work_Room_win.cpp \
		moc/moc_Corridor_win.cpp \
		moc/moc_TCP.cpp \
		moc/moc_Camera.cpp \
		moc/moc_Room.cpp
OBJECTS       = obj/info_widget.o \
		obj/main.o \
		obj/MainWindow.o \
		obj/Bath_Room_win.o \
		obj/Bed_Room_win.o \
		obj/Work_Room_win.o \
		obj/Corridor_win.o \
		obj/TCP.o \
		obj/Room.o \
		obj/Alarm.o \
		obj/Logger.o \
		obj/Camera.o \
		obj/qrc_res.o \
		obj/moc_info_widget.o \
		obj/moc_MainWindow.o \
		obj/moc_Bath_Room_win.o \
		obj/moc_Bed_Room_win.o \
		obj/moc_Work_Room_win.o \
		obj/moc_Corridor_win.o \
		obj/moc_TCP.o \
		obj/moc_Camera.o \
		obj/moc_Room.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		/usr/lib/qt/mkspecs/features/silent.prf \
		namas_main.pro include/build_number.h \
		include/info_widget.h \
		include/MainWindow.h \
		include/Pinctrl.h \
		include/Bath_Room_win.h \
		include/Bed_Room_win.h \
		include/Work_Room_win.h \
		include/Corridor_win.h \
		include/TCP.h \
		include/Camera.h \
		include/Room.h \
		include/Alarm.h \
		include/Logger.h \
		ui/ui_info_widget.h \
		ui/ui_MainWindow.h \
		ui/ui_Bath_Room_win.h src/info_widget.cpp \
		src/main.cpp \
		src/MainWindow.cpp \
		src/Bath_Room_win.cpp \
		src/Bed_Room_win.cpp \
		src/Work_Room_win.cpp \
		src/Corridor_win.cpp \
		src/TCP.cpp \
		src/Room.cpp \
		src/Alarm.cpp \
		src/Logger.cpp \
		src/Camera.cpp
QMAKE_TARGET  = namas_main
DESTDIR       = build/
TARGET        = build/namas_main


first: all
####### Build rules

$(TARGET): ui/ui_info_widget.h ui/ui_MainWindow.h ui/ui_Bath_Room_win.h ui/ui_Bed_Room_win.h ui/ui_Corridor_win.h ui/ui_Work_Room_win.h $(OBJECTS)  
	@test -d build/ || mkdir -p build/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: namas_main.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		/usr/lib/qt/mkspecs/features/silent.prf \
		namas_main.pro \
		resources/res.qrc \
		/usr/lib/libQt5MultimediaWidgets.prl \
		/usr/lib/libQt5Widgets.prl \
		/usr/lib/libQt5Multimedia.prl \
		/usr/lib/libQt5Gui.prl \
		/usr/lib/libQt5Network.prl \
		/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile namas_main.pro CONFIG+=PC
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
/usr/lib/qt/mkspecs/features/silent.prf:
namas_main.pro:
resources/res.qrc:
/usr/lib/libQt5MultimediaWidgets.prl:
/usr/lib/libQt5Widgets.prl:
/usr/lib/libQt5Multimedia.prl:
/usr/lib/libQt5Gui.prl:
/usr/lib/libQt5Network.prl:
/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile namas_main.pro CONFIG+=PC

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/build_number.h include/info_widget.h include/MainWindow.h include/Pinctrl.h include/Bath_Room_win.h include/Bed_Room_win.h include/Work_Room_win.h include/Corridor_win.h include/TCP.h include/Camera.h include/Room.h include/Alarm.h include/Logger.h ui/ui_info_widget.h ui/ui_MainWindow.h ui/ui_Bath_Room_win.h $(DISTDIR)/
	$(COPY_FILE) --parents src/info_widget.cpp src/main.cpp src/MainWindow.cpp src/Bath_Room_win.cpp src/Bed_Room_win.cpp src/Work_Room_win.cpp src/Corridor_win.cpp src/TCP.cpp src/Room.cpp src/Alarm.cpp src/Logger.cpp src/Camera.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/info_widget.ui ui/MainWindow.ui ui/Bath_Room_win.ui ui/Bed_Room_win.ui ui/Corridor_win.ui ui/Work_Room_win.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: rcc/qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc/qrc_res.cpp
rcc/qrc_res.cpp: resources/res.qrc \
		/usr/bin/rcc \
		resources/digital.ttf \
		resources/camera.png \
		resources/home-security.png \
		resources/checkmark.png \
		resources/play.png \
		resources/fan.png \
		resources/unlocked.png \
		resources/mirror_on.png \
		resources/humidity.png \
		resources/checkbox.png \
		resources/temp.png \
		resources/bulb_on.png \
		resources/bulb_off.png \
		resources/fan_on.png \
		resources/mirror.png \
		resources/locked.png \
		resources/home1.png \
		resources/settings.png
	@echo rcc resources/res.qrc && /usr/bin/rcc -name res resources/res.qrc -o rcc/qrc_res.cpp

compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	@echo generating moc/moc_predefs.h
	@g++ -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -W -dM -E -o moc/moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_info_widget.cpp moc/moc_MainWindow.cpp moc/moc_Bath_Room_win.cpp moc/moc_Bed_Room_win.cpp moc/moc_Work_Room_win.cpp moc/moc_Corridor_win.cpp moc/moc_TCP.cpp moc/moc_Camera.cpp moc/moc_Room.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_info_widget.cpp moc/moc_MainWindow.cpp moc/moc_Bath_Room_win.cpp moc/moc_Bed_Room_win.cpp moc/moc_Work_Room_win.cpp moc/moc_Corridor_win.cpp moc/moc_TCP.cpp moc/moc_Camera.cpp moc/moc_Room.cpp
moc/moc_info_widget.cpp: ui/ui_info_widget.h \
		include/TCP.h \
		include/definitions.h \
		include/info_widget.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	@echo moc include/info_widget.h && /usr/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/info_widget.h -o moc/moc_info_widget.cpp

moc/moc_MainWindow.cpp: ui/ui_MainWindow.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/definitions.h \
		include/Bath_Room_win.h \
		ui/ui_Bath_Room_win.h \
		include/Room.h \
		include/Bed_Room_win.h \
		ui/ui_Bed_Room_win.h \
		include/Corridor_win.h \
		ui/ui_Corridor_win.h \
		include/Living_Room_win.h \
		include/Work_Room_win.h \
		ui/ui_Work_Room_win.h \
		include/Camera.h \
		include/GPIO.h \
		include/Alarm.h \
		include/MainWindow.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	@echo moc include/MainWindow.h && /usr/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/MainWindow.h -o moc/moc_MainWindow.cpp

moc/moc_Bath_Room_win.cpp: ui/ui_Bath_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/Bath_Room_win.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	@echo moc include/Bath_Room_win.h && /usr/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Bath_Room_win.h -o moc/moc_Bath_Room_win.cpp

moc/moc_Bed_Room_win.cpp: ui/ui_Bed_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/Bed_Room_win.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	@echo moc include/Bed_Room_win.h && /usr/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Bed_Room_win.h -o moc/moc_Bed_Room_win.cpp

moc/moc_Work_Room_win.cpp: ui/ui_Work_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/Work_Room_win.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	@echo moc include/Work_Room_win.h && /usr/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Work_Room_win.h -o moc/moc_Work_Room_win.cpp

moc/moc_Corridor_win.cpp: ui/ui_Corridor_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/Corridor_win.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	@echo moc include/Corridor_win.h && /usr/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Corridor_win.h -o moc/moc_Corridor_win.cpp

moc/moc_TCP.cpp: include/TCP.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	@echo moc include/TCP.h && /usr/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/TCP.h -o moc/moc_TCP.cpp

moc/moc_Camera.cpp: include/Camera.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	@echo moc include/Camera.h && /usr/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Camera.h -o moc/moc_Camera.cpp

moc/moc_Room.cpp: include/TCP.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/definitions.h \
		include/Room.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	@echo moc include/Room.h && /usr/bin/moc $(DEFINES) --include moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Room.h -o moc/moc_Room.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/ui_info_widget.h ui/ui_MainWindow.h ui/ui_Bath_Room_win.h ui/ui_Bed_Room_win.h ui/ui_Corridor_win.h ui/ui_Work_Room_win.h
compiler_uic_clean:
	-$(DEL_FILE) ui/ui_info_widget.h ui/ui_MainWindow.h ui/ui_Bath_Room_win.h ui/ui_Bed_Room_win.h ui/ui_Corridor_win.h ui/ui_Work_Room_win.h
ui/ui_info_widget.h: ui/info_widget.ui \
		/usr/bin/uic
	@echo uic ui/info_widget.ui && /usr/bin/uic ui/info_widget.ui -o ui/ui_info_widget.h

ui/ui_MainWindow.h: ui/MainWindow.ui \
		/usr/bin/uic \
		include/info_widget.h \
		/usr/include/qt/QtMultimediaWidgets/QVideoWidget \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/definitions.h
	@echo uic ui/MainWindow.ui && /usr/bin/uic ui/MainWindow.ui -o ui/ui_MainWindow.h

ui/ui_Bath_Room_win.h: ui/Bath_Room_win.ui \
		/usr/bin/uic
	@echo uic ui/Bath_Room_win.ui && /usr/bin/uic ui/Bath_Room_win.ui -o ui/ui_Bath_Room_win.h

ui/ui_Bed_Room_win.h: ui/Bed_Room_win.ui \
		/usr/bin/uic
	@echo uic ui/Bed_Room_win.ui && /usr/bin/uic ui/Bed_Room_win.ui -o ui/ui_Bed_Room_win.h

ui/ui_Corridor_win.h: ui/Corridor_win.ui \
		/usr/bin/uic
	@echo uic ui/Corridor_win.ui && /usr/bin/uic ui/Corridor_win.ui -o ui/ui_Corridor_win.h

ui/ui_Work_Room_win.h: ui/Work_Room_win.ui \
		/usr/bin/uic
	@echo uic ui/Work_Room_win.ui && /usr/bin/uic ui/Work_Room_win.ui -o ui/ui_Work_Room_win.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/info_widget.o: src/info_widget.cpp include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/definitions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/info_widget.o src/info_widget.cpp

obj/main.o: src/main.cpp include/MainWindow.h \
		ui/ui_MainWindow.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/definitions.h \
		include/Bath_Room_win.h \
		ui/ui_Bath_Room_win.h \
		include/Room.h \
		include/Bed_Room_win.h \
		ui/ui_Bed_Room_win.h \
		include/Corridor_win.h \
		ui/ui_Corridor_win.h \
		include/Living_Room_win.h \
		include/Work_Room_win.h \
		ui/ui_Work_Room_win.h \
		include/Camera.h \
		include/GPIO.h \
		include/Alarm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/MainWindow.o: src/MainWindow.cpp include/MainWindow.h \
		ui/ui_MainWindow.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/definitions.h \
		include/Bath_Room_win.h \
		ui/ui_Bath_Room_win.h \
		include/Room.h \
		include/Bed_Room_win.h \
		ui/ui_Bed_Room_win.h \
		include/Corridor_win.h \
		ui/ui_Corridor_win.h \
		include/Living_Room_win.h \
		include/Work_Room_win.h \
		ui/ui_Work_Room_win.h \
		include/Camera.h \
		include/GPIO.h \
		include/Alarm.h \
		include/Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MainWindow.o src/MainWindow.cpp

obj/Bath_Room_win.o: src/Bath_Room_win.cpp include/Bath_Room_win.h \
		ui/ui_Bath_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Bath_Room_win.o src/Bath_Room_win.cpp

obj/Bed_Room_win.o: src/Bed_Room_win.cpp include/Bed_Room_win.h \
		ui/ui_Bed_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Bed_Room_win.o src/Bed_Room_win.cpp

obj/Work_Room_win.o: src/Work_Room_win.cpp include/Work_Room_win.h \
		ui/ui_Work_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Work_Room_win.o src/Work_Room_win.cpp

obj/Corridor_win.o: src/Corridor_win.cpp include/Corridor_win.h \
		ui/ui_Corridor_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Corridor_win.o src/Corridor_win.cpp

obj/TCP.o: src/TCP.cpp include/TCP.h \
		include/Bath_Room_win.h \
		ui/ui_Bath_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/Room.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/TCP.o src/TCP.cpp

obj/Room.o: src/Room.cpp include/Room.h \
		include/TCP.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/definitions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Room.o src/Room.cpp

obj/Alarm.o: src/Alarm.cpp include/Alarm.h \
		include/Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Alarm.o src/Alarm.cpp

obj/Logger.o: src/Logger.cpp include/Logger.h \
		include/Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Logger.o src/Logger.cpp

obj/Camera.o: src/Camera.cpp include/Camera.h \
		include/Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Camera.o src/Camera.cpp

obj/qrc_res.o: rcc/qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_res.o rcc/qrc_res.cpp

obj/moc_info_widget.o: moc/moc_info_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_info_widget.o moc/moc_info_widget.cpp

obj/moc_MainWindow.o: moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_MainWindow.o moc/moc_MainWindow.cpp

obj/moc_Bath_Room_win.o: moc/moc_Bath_Room_win.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Bath_Room_win.o moc/moc_Bath_Room_win.cpp

obj/moc_Bed_Room_win.o: moc/moc_Bed_Room_win.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Bed_Room_win.o moc/moc_Bed_Room_win.cpp

obj/moc_Work_Room_win.o: moc/moc_Work_Room_win.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Work_Room_win.o moc/moc_Work_Room_win.cpp

obj/moc_Corridor_win.o: moc/moc_Corridor_win.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Corridor_win.o moc/moc_Corridor_win.cpp

obj/moc_TCP.o: moc/moc_TCP.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_TCP.o moc/moc_TCP.cpp

obj/moc_Camera.o: moc/moc_Camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Camera.o moc/moc_Camera.cpp

obj/moc_Room.o: moc/moc_Room.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Room.o moc/moc_Room.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

