#############################################################################
# Makefile for building: build/namas_main
# Generated by qmake (3.1) (Qt 5.13.1)
# Project:  namas_main.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile namas_main.pro CONFIG+=PC
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DPC -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -O2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -Isrc -Iinclude -Iui -Ilib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -isystem /usr/local/include -isystem /usr/include/qt -isystem /usr/include/qt/QtMultimediaWidgets -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtMultimedia -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtWebSockets -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtCore -Imoc -isystem /usr/include/libdrm -Iui -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = namas_main1.0.0
DISTDIR = /home/justas/work/namas/namas_main/obj/namas_main1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) /usr/lib/libQt5MultimediaWidgets.so /usr/lib/libQt5Widgets.so /usr/lib/libQt5Multimedia.so /usr/lib/libQt5Gui.so /usr/lib/libQt5WebSockets.so /usr/lib/libQt5Network.so /usr/lib/libQt5Xml.so /usr/lib/libQt5Core.so /usr/lib/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/info_widget.cpp \
		src/main.cpp \
		src/MainWindow.cpp \
		src/Bath_Room_win.cpp \
		src/Bed_Room_win.cpp \
		src/Living_Room_win.cpp \
		src/Work_Room_win.cpp \
		src/Corridor_win.cpp \
		src/TCP.cpp \
		src/Room.cpp \
		src/Alarm.cpp \
		src/GPIO.cpp \
		src/Logger.cpp \
		src/Blank_widget.cpp \
		src/DataLogger.cpp \
		src/tcp_server.cpp \
		src/Settings.cpp \
		src/UserManager.cpp \
		src/Utils.cpp \
		src/miniaes.cpp \
		src/Camera.cpp \
		src/ws_server.cpp rcc/qrc_res.cpp \
		moc/moc_info_widget.cpp \
		moc/moc_MainWindow.cpp \
		moc/moc_Bath_Room_win.cpp \
		moc/moc_Bed_Room_win.cpp \
		moc/moc_Living_Room_win.cpp \
		moc/moc_Work_Room_win.cpp \
		moc/moc_Corridor_win.cpp \
		moc/moc_TCP.cpp \
		moc/moc_Camera.cpp \
		moc/moc_Room.cpp \
		moc/moc_GPIO.cpp \
		moc/moc_Blank_widget.cpp \
		moc/moc_DataLogger.cpp \
		moc/moc_tcp_server.cpp \
		moc/moc_ws_server.cpp
OBJECTS       = obj/info_widget.o \
		obj/main.o \
		obj/MainWindow.o \
		obj/Bath_Room_win.o \
		obj/Bed_Room_win.o \
		obj/Living_Room_win.o \
		obj/Work_Room_win.o \
		obj/Corridor_win.o \
		obj/TCP.o \
		obj/Room.o \
		obj/Alarm.o \
		obj/GPIO.o \
		obj/Logger.o \
		obj/Blank_widget.o \
		obj/DataLogger.o \
		obj/tcp_server.o \
		obj/Settings.o \
		obj/UserManager.o \
		obj/Utils.o \
		obj/miniaes.o \
		obj/Camera.o \
		obj/ws_server.o \
		obj/qrc_res.o \
		obj/moc_info_widget.o \
		obj/moc_MainWindow.o \
		obj/moc_Bath_Room_win.o \
		obj/moc_Bed_Room_win.o \
		obj/moc_Living_Room_win.o \
		obj/moc_Work_Room_win.o \
		obj/moc_Corridor_win.o \
		obj/moc_TCP.o \
		obj/moc_Camera.o \
		obj/moc_Room.o \
		obj/moc_GPIO.o \
		obj/moc_Blank_widget.o \
		obj/moc_DataLogger.o \
		obj/moc_tcp_server.o \
		obj/moc_ws_server.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		namas_main.pro include/build_number.h \
		include/info_widget.h \
		include/MainWindow.h \
		include/Pinctrl.h \
		include/Bath_Room_win.h \
		include/Bed_Room_win.h \
		include/Living_Room_win.h \
		include/Work_Room_win.h \
		include/Corridor_win.h \
		include/TCP.h \
		include/Camera.h \
		include/Room.h \
		include/Alarm.h \
		include/GPIO.h \
		include/Blank_widget.h \
		include/DataLogger.h \
		include/tcp_server.h \
		include/Settings.h \
		include/UserManager.h \
		include/Utils.h \
		include/miniaes.h \
		include/Logger.h \
		include/ws_server.h \
		include/json.hpp src/info_widget.cpp \
		src/main.cpp \
		src/MainWindow.cpp \
		src/Bath_Room_win.cpp \
		src/Bed_Room_win.cpp \
		src/Living_Room_win.cpp \
		src/Work_Room_win.cpp \
		src/Corridor_win.cpp \
		src/TCP.cpp \
		src/Room.cpp \
		src/Alarm.cpp \
		src/GPIO.cpp \
		src/Logger.cpp \
		src/Blank_widget.cpp \
		src/DataLogger.cpp \
		src/tcp_server.cpp \
		src/Settings.cpp \
		src/UserManager.cpp \
		src/Utils.cpp \
		src/miniaes.cpp \
		src/Camera.cpp \
		src/ws_server.cpp
QMAKE_TARGET  = namas_main
DESTDIR       = build/
TARGET        = build/namas_main


first: all
####### Build rules

build/namas_main: build_nr ui/ui_info_widget.h ui/ui_MainWindow.h ui/ui_Bath_Room_win.h ui/ui_Bed_Room_win.h ui/ui_Living_Room_win.h ui/ui_Corridor_win.h ui/ui_Blank_widget.h ui/ui_Work_Room_win.h $(OBJECTS)  
	@test -d build/ || mkdir -p build/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: namas_main.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		namas_main.pro \
		resources/res.qrc
	$(QMAKE) -o Makefile namas_main.pro CONFIG+=PC
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scxml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
namas_main.pro:
resources/res.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile namas_main.pro CONFIG+=PC

qmake_all: FORCE


all: Makefile build/namas_main

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/build_number.h include/info_widget.h include/MainWindow.h include/Pinctrl.h include/Bath_Room_win.h include/Bed_Room_win.h include/Living_Room_win.h include/Work_Room_win.h include/Corridor_win.h include/TCP.h include/Camera.h include/Room.h include/Alarm.h include/GPIO.h include/Blank_widget.h include/DataLogger.h include/tcp_server.h include/Settings.h include/UserManager.h include/Utils.h include/miniaes.h include/Logger.h include/ws_server.h include/json.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/info_widget.cpp src/main.cpp src/MainWindow.cpp src/Bath_Room_win.cpp src/Bed_Room_win.cpp src/Living_Room_win.cpp src/Work_Room_win.cpp src/Corridor_win.cpp src/TCP.cpp src/Room.cpp src/Alarm.cpp src/GPIO.cpp src/Logger.cpp src/Blank_widget.cpp src/DataLogger.cpp src/tcp_server.cpp src/Settings.cpp src/UserManager.cpp src/Utils.cpp src/miniaes.cpp src/Camera.cpp src/ws_server.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/info_widget.ui ui/MainWindow.ui ui/Bath_Room_win.ui ui/Bed_Room_win.ui ui/Living_Room_win.ui ui/Corridor_win.ui ui/Blank_widget.ui ui/Work_Room_win.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

build_nr: FORCE
	./build_number.sh

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: rcc/qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc/qrc_res.cpp
rcc/qrc_res.cpp: resources/res.qrc \
		/usr/bin/rcc \
		resources/digital.ttf \
		resources/switch_on.png \
		resources/bulb_off.png \
		resources/play.png \
		resources/fan_on.png \
		resources/green-circle.png \
		resources/home1.png \
		resources/temp.png \
		resources/camera.png \
		resources/home-security.png \
		resources/switch_off.png \
		resources/humidity.png \
		resources/settings.png \
		resources/checkmark.png \
		resources/unlocked.png \
		resources/checkbox.png \
		resources/bulb_on.png \
		resources/mirror.png \
		resources/locked.png \
		resources/fan.png \
		resources/mirror_on.png
	/usr/bin/rcc -name res resources/res.qrc -o rcc/qrc_res.cpp

compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++0x -O2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -W -dM -E -o moc/moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_info_widget.cpp moc/moc_MainWindow.cpp moc/moc_Bath_Room_win.cpp moc/moc_Bed_Room_win.cpp moc/moc_Living_Room_win.cpp moc/moc_Work_Room_win.cpp moc/moc_Corridor_win.cpp moc/moc_TCP.cpp moc/moc_Camera.cpp moc/moc_Room.cpp moc/moc_GPIO.cpp moc/moc_Blank_widget.cpp moc/moc_DataLogger.cpp moc/moc_tcp_server.cpp moc/moc_ws_server.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_info_widget.cpp moc/moc_MainWindow.cpp moc/moc_Bath_Room_win.cpp moc/moc_Bed_Room_win.cpp moc/moc_Living_Room_win.cpp moc/moc_Work_Room_win.cpp moc/moc_Corridor_win.cpp moc/moc_TCP.cpp moc/moc_Camera.cpp moc/moc_Room.cpp moc/moc_GPIO.cpp moc/moc_Blank_widget.cpp moc/moc_DataLogger.cpp moc/moc_tcp_server.cpp moc/moc_ws_server.cpp
moc/moc_info_widget.cpp: include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/definitions.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/info_widget.h -o moc/moc_info_widget.cpp

moc/moc_MainWindow.cpp: include/MainWindow.h \
		ui/ui_MainWindow.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/definitions.h \
		include/Bath_Room_win.h \
		ui/ui_Bath_Room_win.h \
		include/Room.h \
		include/DataLogger.h \
		include/Bed_Room_win.h \
		ui/ui_Bed_Room_win.h \
		include/Corridor_win.h \
		ui/ui_Corridor_win.h \
		include/Living_Room_win.h \
		ui/ui_Living_Room_win.h \
		include/Work_Room_win.h \
		ui/ui_Work_Room_win.h \
		include/Camera.h \
		include/GPIO.h \
		include/Blank_widget.h \
		ui/ui_Blank_widget.h \
		include/Alarm.h \
		include/tcp_server.h \
		include/ws_server.h \
		include/Settings.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/MainWindow.h -o moc/moc_MainWindow.cpp

moc/moc_Bath_Room_win.cpp: include/Bath_Room_win.h \
		ui/ui_Bath_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/DataLogger.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Bath_Room_win.h -o moc/moc_Bath_Room_win.cpp

moc/moc_Bed_Room_win.cpp: include/Bed_Room_win.h \
		ui/ui_Bed_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/DataLogger.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Bed_Room_win.h -o moc/moc_Bed_Room_win.cpp

moc/moc_Living_Room_win.cpp: include/Living_Room_win.h \
		ui/ui_Living_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/DataLogger.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Living_Room_win.h -o moc/moc_Living_Room_win.cpp

moc/moc_Work_Room_win.cpp: include/Work_Room_win.h \
		ui/ui_Work_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/DataLogger.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Work_Room_win.h -o moc/moc_Work_Room_win.cpp

moc/moc_Corridor_win.cpp: include/Corridor_win.h \
		ui/ui_Corridor_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/DataLogger.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Corridor_win.h -o moc/moc_Corridor_win.cpp

moc/moc_TCP.cpp: include/TCP.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/TCP.h -o moc/moc_TCP.cpp

moc/moc_Camera.cpp: include/Camera.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Camera.h -o moc/moc_Camera.cpp

moc/moc_Room.cpp: include/Room.h \
		include/TCP.h \
		include/DataLogger.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Room.h -o moc/moc_Room.cpp

moc/moc_GPIO.cpp: include/GPIO.h \
		include/Blank_widget.h \
		ui/ui_Blank_widget.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/GPIO.h -o moc/moc_GPIO.cpp

moc/moc_Blank_widget.cpp: include/Blank_widget.h \
		ui/ui_Blank_widget.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/Blank_widget.h -o moc/moc_Blank_widget.cpp

moc/moc_DataLogger.cpp: include/DataLogger.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/DataLogger.h -o moc/moc_DataLogger.cpp

moc/moc_tcp_server.cpp: include/tcp_server.h \
		include/definitions.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/tcp_server.h -o moc/moc_tcp_server.cpp

moc/moc_ws_server.cpp: include/ws_server.h \
		moc/moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/justas/work/namas/namas_main/moc/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main -I/home/justas/work/namas/namas_main/src -I/home/justas/work/namas/namas_main/include -I/home/justas/work/namas/namas_main/ui -I/home/justas/work/namas/namas_main/lib -I/home/justas/sdk/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi/usr/include -I/usr/local/include -I/usr/include/qt -I/usr/include/qt/QtMultimediaWidgets -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebSockets -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtXml -I/usr/include/qt/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include -I/usr/include/c++/7.1.1 -I/usr/include/c++/7.1.1/i686-pc-linux-gnu -I/usr/include/c++/7.1.1/backward -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/7.1.1/include-fixed -I/usr/include include/ws_server.h -o moc/moc_ws_server.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/ui_info_widget.h ui/ui_MainWindow.h ui/ui_Bath_Room_win.h ui/ui_Bed_Room_win.h ui/ui_Living_Room_win.h ui/ui_Corridor_win.h ui/ui_Blank_widget.h ui/ui_Work_Room_win.h
compiler_uic_clean:
	-$(DEL_FILE) ui/ui_info_widget.h ui/ui_MainWindow.h ui/ui_Bath_Room_win.h ui/ui_Bed_Room_win.h ui/ui_Living_Room_win.h ui/ui_Corridor_win.h ui/ui_Blank_widget.h ui/ui_Work_Room_win.h
ui/ui_info_widget.h: ui/info_widget.ui \
		/usr/bin/uic
	/usr/bin/uic ui/info_widget.ui -o ui/ui_info_widget.h

ui/ui_MainWindow.h: ui/MainWindow.ui \
		/usr/bin/uic \
		include/info_widget.h \
		/usr/include/qt/QtMultimediaWidgets/QVideoWidget \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/definitions.h
	/usr/bin/uic ui/MainWindow.ui -o ui/ui_MainWindow.h

ui/ui_Bath_Room_win.h: ui/Bath_Room_win.ui \
		/usr/bin/uic
	/usr/bin/uic ui/Bath_Room_win.ui -o ui/ui_Bath_Room_win.h

ui/ui_Bed_Room_win.h: ui/Bed_Room_win.ui \
		/usr/bin/uic
	/usr/bin/uic ui/Bed_Room_win.ui -o ui/ui_Bed_Room_win.h

ui/ui_Living_Room_win.h: ui/Living_Room_win.ui \
		/usr/bin/uic
	/usr/bin/uic ui/Living_Room_win.ui -o ui/ui_Living_Room_win.h

ui/ui_Corridor_win.h: ui/Corridor_win.ui \
		/usr/bin/uic
	/usr/bin/uic ui/Corridor_win.ui -o ui/ui_Corridor_win.h

ui/ui_Blank_widget.h: ui/Blank_widget.ui \
		/usr/bin/uic
	/usr/bin/uic ui/Blank_widget.ui -o ui/ui_Blank_widget.h

ui/ui_Work_Room_win.h: ui/Work_Room_win.ui \
		/usr/bin/uic
	/usr/bin/uic ui/Work_Room_win.ui -o ui/ui_Work_Room_win.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

obj/info_widget.o: src/info_widget.cpp include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/definitions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/info_widget.o src/info_widget.cpp

obj/main.o: src/main.cpp include/MainWindow.h \
		ui/ui_MainWindow.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/definitions.h \
		include/Bath_Room_win.h \
		ui/ui_Bath_Room_win.h \
		include/Room.h \
		include/DataLogger.h \
		include/Bed_Room_win.h \
		ui/ui_Bed_Room_win.h \
		include/Corridor_win.h \
		ui/ui_Corridor_win.h \
		include/Living_Room_win.h \
		ui/ui_Living_Room_win.h \
		include/Work_Room_win.h \
		ui/ui_Work_Room_win.h \
		include/Camera.h \
		include/GPIO.h \
		include/Blank_widget.h \
		ui/ui_Blank_widget.h \
		include/Alarm.h \
		include/tcp_server.h \
		include/ws_server.h \
		include/Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/MainWindow.o: src/MainWindow.cpp include/MainWindow.h \
		ui/ui_MainWindow.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/definitions.h \
		include/Bath_Room_win.h \
		ui/ui_Bath_Room_win.h \
		include/Room.h \
		include/DataLogger.h \
		include/Bed_Room_win.h \
		ui/ui_Bed_Room_win.h \
		include/Corridor_win.h \
		ui/ui_Corridor_win.h \
		include/Living_Room_win.h \
		ui/ui_Living_Room_win.h \
		include/Work_Room_win.h \
		ui/ui_Work_Room_win.h \
		include/Camera.h \
		include/GPIO.h \
		include/Blank_widget.h \
		ui/ui_Blank_widget.h \
		include/Alarm.h \
		include/tcp_server.h \
		include/ws_server.h \
		include/Settings.h \
		include/Logger.h \
		include/Config.h \
		include/UserManager.h \
		include/build_number.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MainWindow.o src/MainWindow.cpp

obj/Bath_Room_win.o: src/Bath_Room_win.cpp include/Bath_Room_win.h \
		ui/ui_Bath_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/DataLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Bath_Room_win.o src/Bath_Room_win.cpp

obj/Bed_Room_win.o: src/Bed_Room_win.cpp include/Bed_Room_win.h \
		ui/ui_Bed_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/DataLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Bed_Room_win.o src/Bed_Room_win.cpp

obj/Living_Room_win.o: src/Living_Room_win.cpp include/Living_Room_win.h \
		ui/ui_Living_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/DataLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Living_Room_win.o src/Living_Room_win.cpp

obj/Work_Room_win.o: src/Work_Room_win.cpp include/Work_Room_win.h \
		ui/ui_Work_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/DataLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Work_Room_win.o src/Work_Room_win.cpp

obj/Corridor_win.o: src/Corridor_win.cpp include/Corridor_win.h \
		ui/ui_Corridor_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Room.h \
		include/DataLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Corridor_win.o src/Corridor_win.cpp

obj/TCP.o: src/TCP.cpp include/TCP.h \
		include/Bath_Room_win.h \
		ui/ui_Bath_Room_win.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/Room.h \
		include/DataLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/TCP.o src/TCP.cpp

obj/Room.o: src/Room.cpp include/Room.h \
		include/TCP.h \
		include/DataLogger.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Room.o src/Room.cpp

obj/Alarm.o: src/Alarm.cpp include/Alarm.h \
		include/Config.h \
		include/UserManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Alarm.o src/Alarm.cpp

obj/GPIO.o: src/GPIO.cpp include/GPIO.h \
		include/Blank_widget.h \
		ui/ui_Blank_widget.h \
		include/Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GPIO.o src/GPIO.cpp

obj/Logger.o: src/Logger.cpp include/Logger.h \
		include/Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Logger.o src/Logger.cpp

obj/Blank_widget.o: src/Blank_widget.cpp include/Blank_widget.h \
		ui/ui_Blank_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Blank_widget.o src/Blank_widget.cpp

obj/DataLogger.o: src/DataLogger.cpp include/DataLogger.h \
		include/definitions.h \
		include/info_widget.h \
		ui/ui_info_widget.h \
		include/TCP.h \
		include/Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/DataLogger.o src/DataLogger.cpp

obj/tcp_server.o: src/tcp_server.cpp include/tcp_server.h \
		include/definitions.h \
		include/Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tcp_server.o src/tcp_server.cpp

obj/Settings.o: src/Settings.cpp include/Settings.h \
		include/tcp_server.h \
		include/definitions.h \
		include/Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Settings.o src/Settings.cpp

obj/UserManager.o: src/UserManager.cpp include/UserManager.h \
		include/Config.h \
		include/Utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/UserManager.o src/UserManager.cpp

obj/Utils.o: src/Utils.cpp include/Utils.h \
		include/miniaes.h \
		include/Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Utils.o src/Utils.cpp

obj/miniaes.o: src/miniaes.cpp include/miniaes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/miniaes.o src/miniaes.cpp

obj/Camera.o: src/Camera.cpp include/Camera.h \
		include/Config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Camera.o src/Camera.cpp

obj/ws_server.o: src/ws_server.cpp include/ws_server.h \
		include/json.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ws_server.o src/ws_server.cpp

obj/qrc_res.o: rcc/qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_res.o rcc/qrc_res.cpp

obj/moc_info_widget.o: moc/moc_info_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_info_widget.o moc/moc_info_widget.cpp

obj/moc_MainWindow.o: moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_MainWindow.o moc/moc_MainWindow.cpp

obj/moc_Bath_Room_win.o: moc/moc_Bath_Room_win.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Bath_Room_win.o moc/moc_Bath_Room_win.cpp

obj/moc_Bed_Room_win.o: moc/moc_Bed_Room_win.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Bed_Room_win.o moc/moc_Bed_Room_win.cpp

obj/moc_Living_Room_win.o: moc/moc_Living_Room_win.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Living_Room_win.o moc/moc_Living_Room_win.cpp

obj/moc_Work_Room_win.o: moc/moc_Work_Room_win.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Work_Room_win.o moc/moc_Work_Room_win.cpp

obj/moc_Corridor_win.o: moc/moc_Corridor_win.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Corridor_win.o moc/moc_Corridor_win.cpp

obj/moc_TCP.o: moc/moc_TCP.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_TCP.o moc/moc_TCP.cpp

obj/moc_Camera.o: moc/moc_Camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Camera.o moc/moc_Camera.cpp

obj/moc_Room.o: moc/moc_Room.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Room.o moc/moc_Room.cpp

obj/moc_GPIO.o: moc/moc_GPIO.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_GPIO.o moc/moc_GPIO.cpp

obj/moc_Blank_widget.o: moc/moc_Blank_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Blank_widget.o moc/moc_Blank_widget.cpp

obj/moc_DataLogger.o: moc/moc_DataLogger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_DataLogger.o moc/moc_DataLogger.cpp

obj/moc_tcp_server.o: moc/moc_tcp_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_tcp_server.o moc/moc_tcp_server.cpp

obj/moc_ws_server.o: moc/moc_ws_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_ws_server.o moc/moc_ws_server.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

